packages:
  - client
  - admin
  - server
  - shared/*
allowBuilds:
  '@firebase/util': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
catalog:
  '@hookform/resolvers': ^5.2.2
  '@tanstack/react-query': ^5.90.5
  axios: ^1.16.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dayjs: ^1.11.21
  framer-motion: ^12.39.0
  next: ^16.2.2
  next-themes: ^0.4.6
  nuqs: ^2.8.9
  react: ^19.2.4
  react-day-picker: ^9.11.1
  react-dom: ^19.2.4
  react-hook-form: ^7.71.1
  react-icons: ^5.5.0
  react-loading-skeleton: ^3.5.0
  react-merge-refs: ^3.0.2
  react-textarea-autosize: ^8.5.9
  react-toastify: ^11.0.5
  sass: ^1.93.2
  zod: ^4.1.12
  zustand: ^5.0.8
  '@eslint/eslintrc': ^3.3.5
  '@eslint/js': ^10.0.1
  '@types/node': ^25.5.2
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  eslint: ^10.1.0
  eslint-config-next: 15.5.6
  eslint-config-prettier: ^10.1.8
  eslint-plugin-oxlint: ^1.68.0
  globals: ^17.4.0
  oxlint: ^1.68.0
  prettier: ^3.8.1
  typescript: ^5.9.3
  typescript-eslint: ^8.58.0
