export const PAGES = {
	HOME: '/',
	LOGIN: '/login',
	USERS: '/users',
	USER: (username: string) => `/users/${username}`,
	REPORTS: '/reports',
	REPORT: (id: string) => `/reports/${id}`,
	NOTIFICATIONS: '/notifications',
	NOTIFICATION: (id: string) => `/notifications/${id}`,
	CUSTOMIZATION: '/customization',
	ITEMS: '/customization/items',
	ITEM: (id: string) => `/customization/items/${id}`,
	ITEM_NEW: '/customization/items/new',
	BUNDLES: '/customization/bundles',
	BUNDLE: (id: string) => `/customization/bundles/${id}`,
	BUNDLE_NEW: '/customization/bundles/new',
	PRODUCTS: '/customization/products',
	PRODUCT: (id: string) => `/customization/products/${id}`,
	PRODUCT_NEW: '/customization/products/new',
	PROMOTIONS: '/promotions',
	PROMOTION: (id: string) => `/promotions/${id}`,
	PROMOTION_NEW: `/promotions/new`,
	ACHIEVEMENTS: '/achievements',
	ACHIEVEMENT: (id: string) => `/achievements/${id}`,
	ACHIEVEMENT_NEW: '/achievements/new',
} as const;
