export const ITEM_TYPES = {
	AVATAR: 'AVATAR',
	AVATAR_FRAME: 'AVATAR_FRAME',
	ANIMATED_AVATAR: 'ANIMATED_AVATAR',
	BACKGROUND_IMAGE: 'BACKGROUND_IMAGE',
	MINI_BACKGROUND_IMAGE: 'MINI_BACKGROUND_IMAGE',
	BADGE: 'BADGE',
} as const;
