import { components } from '../../schema';

type SwaggerNotificationType = components['schemas']['NotificationType'];

export const NotificationType = {
	ACHIEVEMENT_UNLOCKED: 'ACHIEVEMENT_UNLOCKED',
	FRIEND_REQUEST: 'FRIEND_REQUEST',
	INFORMATION: 'INFORMATION',
	MAINTENANCE: 'MAINTENANCE',
	OTHER: 'OTHER',
	MARKETING: 'MARKETING',
	WEEKLY_SUMMARY: 'WEEKLY_SUMMARY',
	PERSONAL_MESSAGE: 'PERSONAL_MESSAGE',
	SANCTION: 'SANCTION',
	UPDATE: 'UPDATE',
	CHALLENGE_COMPLETED: 'CHALLENGE_COMPLETED',
	CHALLENGE_EXPIRED: 'CHALLENGE_EXPIRED',
	CHALLENGE_FAILED: 'CHALLENGE_FAILED',
	CHALLENGE_FROZEN: 'CHALLENGE_FROZEN',
	CHALLENGE_INVITATION: 'CHALLENGE_INVITATION',
	CHALLENGE_RESTORED: 'CHALLENGE_RESTORED',
} as const satisfies Record<SwaggerNotificationType, SwaggerNotificationType>;

export type NotificationType =
	(typeof NotificationType)[keyof typeof NotificationType];
