name: PR Build Check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build ${{ matrix.app }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        app: [client, admin, server]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
          version: 11.7.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        if: ${{ matrix.app == 'server' }}
        run: pnpm --filter server exec prisma generate

      - name: Load Mock Env
        if: ${{ matrix.app != 'server' }}
        run: cp .env.mock .env
        working-directory: apps/${{ matrix.app }}

      - name: Build ${{ matrix.app }}
        run: pnpm --filter ${{ matrix.app }} build
